# Generated by Django 4.2.10 on 2024-06-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.epic'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'CRITICAL'), (2, 'ESSENTIAL'), (3, 'BENEFICIAL'), (4, 'OPTIONAL')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sprint'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'CRITICAL'), (2, 'ESSENTIAL'), (3, 'BENEFICIAL'), (4, 'OPTIONAL')], null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='subtasks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='user_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
