# Generated by Django 4.2.10 on 2024-06-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_task_description_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sprint'),
        ),
    ]
