# Generated by Django 4.2.10 on 2024-06-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_userstory_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='status',
            field=models.IntegerField(choices=[(1, 'TO DO'), (2, 'IN PROGRESS'), (3, 'REVIEW'), (4, 'DONE')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'TO DO'), (2, 'IN PROGRESS'), (3, 'REVIEW'), (4, 'DONE')], default=1),
        ),
        migrations.AddField(
            model_name='userstory',
            name='status',
            field=models.IntegerField(choices=[(1, 'TO DO'), (2, 'IN PROGRESS'), (3, 'REVIEW'), (4, 'DONE')], default=1),
        ),
    ]
