# Generated by Django 4.2.10 on 2024-06-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_epic_status_task_status_userstory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='status',
            field=models.IntegerField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('REVIEW', 'REVIEW'), ('DONE', 'DONE')], default='TO DO'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('REVIEW', 'REVIEW'), ('DONE', 'DONE')], default='TO DO'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.IntegerField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('REVIEW', 'REVIEW'), ('DONE', 'DONE')], default='TO DO'),
        ),
    ]
