# Generated by Django 4.2.10 on 2024-06-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_epic_status_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='priority',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'CRITICAL'), ('ESSENTIAL', 'ESSENTIAL'), ('BENEFICIAL', 'BENEFICIAL'), ('OPTIONAL', 'OPTIONAL')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'CRITICAL'), ('ESSENTIAL', 'ESSENTIAL'), ('BENEFICIAL', 'BENEFICIAL'), ('OPTIONAL', 'OPTIONAL')], null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='priority',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'CRITICAL'), ('ESSENTIAL', 'ESSENTIAL'), ('BENEFICIAL', 'BENEFICIAL'), ('OPTIONAL', 'OPTIONAL')], null=True),
        ),
    ]
