# Generated by Django 4.2.10 on 2024-06-30 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_epic_priority_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='status',
            field=models.CharField(blank=True, choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('REVIEW', 'REVIEW'), ('DONE', 'DONE')], null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.epic'),
        ),
    ]
