# Generated by Django 4.2.10 on 2024-07-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_userstory_acceptance_criteria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStory',
            new_name='Item',
        ),
    ]
